"""rename department

Revision ID: 500799ef389f
Revises: b124bc49bb2d
Create Date: 2025-06-11 11:41:41.339187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500799ef389f'
down_revision = 'b124bc49bb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departemnts', 'department')
    # ### end Alembic commands ###
